server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://sample-db-dev.nalbam.com:1500/sample?useUnicode=true&characterEncoding=utf-8
    username: username
    password: password
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  redis:
    host: dev.redis.nalbam.com
    database: 5
    expire:
      seconds: 3600

eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8080
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

demo:
  password: '{cipher}781f503ee5e7804fcaea686d63d4bfac9fc49dd2891b6a903c4c527b219a86f2'

aws:
  region: ap-northeast-2
  bucket: demo.nalbam.com
